import type { Metadata } from "next";
import Image from "next/image";
export const metadata: Metadata = { title: "Winter Cabin Rentals", description: "Plan a winter cabin stay at Garnet. Find cabin capacities, rental information, and BLM reservation contacts." };
const provided = ["Rodent-proof can", "Firewood and ax", "Water containers", "Two-burner propane cook stove", "Wood-burning heat stove", "Fire extinguisher and smoke alarm", "First aid kit", "Propane light", "Table and chairs", "Beds", "Broom and dust pan", "Snow shovel", "Dish pan, drying rack and drainer", "Frying pans, pots and kettle", "Plates, bowls, cups and glasses", "Silverware, can opener and basic utensils"];
const bring = ["Cabin combination and permit", "Food and beverages", "Warm clothing", "Sleeping bags", "Flashlight", "Emergency shelter", "Sharp knife", "Storm gear", "Towel", "Dish soap and sponge", "Ski repair items", "Snowmobile repair items", "Garbage bags", "Compass", "Toiletries", "Specific first aid or medical supplies"];
export default function CabinRentalsPage() {
  return <main id="main-content" className="bg-[#f4f0e7] text-[#24352b]">
    <section className="bg-[#1e2f1f] px-5 pt-44 pb-12 text-[#f8f6f1] md:px-10 md:pt-48">
      <div className="mx-auto grid max-w-[82rem] items-center gap-10 lg:grid-cols-2">
        <div><p className="text-sm font-semibold text-[#e0c46d]">Stay at Garnet</p><h1 className="display-type mt-4 text-5xl leading-tight md:text-6xl">Winter cabin rentals</h1><p className="mt-5 text-lg leading-8 text-white/80">Two primitive BLM cabins, December 1 to April 30. Reach Garnet by skis, snowshoes, or snowmobile; wheeled vehicles cannot access town in winter.</p><a href="tel:4063293914" className="mt-6 inline-block border-b border-[#e0c46d] pb-2 font-semibold">Call the BLM: 406.329.3914</a></div>
        <figure><div className="relative aspect-[4/3] overflow-hidden"><Image src="/images/historic/university-archive/garnet-ghost-town-hillside-buildings-in-winter-77-0004.webp" alt="Historic photograph of Garnet’s hillside buildings in winter" fill priority sizes="(min-width: 1024px) 45vw, 90vw" className="object-cover" /></div><figcaption className="mt-3 text-xs text-white/70">Historic winter view. Courtesy of University of Montana.</figcaption></figure>
      </div>
    </section>
    <section className="mx-auto max-w-[82rem] px-5 py-12 md:px-10 md:py-16">
      <h2 className="display-type text-4xl md:text-5xl">Do you want to sleep with the ghosts?</h2>
      <p className="mt-5 max-w-3xl text-lg leading-8 text-[#625b50]">Two primitive cabins are available from December 1 to April 30. They are heated by wood stoves and lit by propane lights. Neither has electricity or indoor plumbing. Outhouses and drinking water are near the cabins. Each cabin has cooking utensils and a propane stove.</p>
      <div className="mt-10 grid gap-8 sm:grid-cols-2">{[["Dahl Cabin", "Up to 6 guests", "Two full beds and two cots."], ["McDonald Cabin", "Up to 4 guests", "A single room with two double beds."]].map(([name, capacity, beds]) => <article key={name} className="border-t-4 border-[#a36b43] pt-5"><h3 className="display-type text-4xl">{name}</h3><p className="mt-4 text-lg font-semibold">{capacity} · $50 per night</p><p className="mt-3 leading-7 text-[#625b50]">{beds}</p></article>)}</div>
      <aside className="mt-10 border-l-4 border-[#3d5a3e] bg-[#e9e1d1] p-6"><h3 className="text-xl font-semibold">Winter access</h3><p className="mt-3 max-w-3xl leading-7">Garnet is not accessible by wheeled vehicles during winter. You will need to travel by snowmobile, skis, or snowshoes.</p></aside>
      <div className="mt-12 grid gap-10 border-t border-[#24352b]/20 pt-10 lg:grid-cols-[1fr_1.4fr]">
        <div><h2 className="display-type text-4xl">How reservations work</h2><p className="mt-4 leading-7 text-[#625b50]">Popular weekends are assigned through a lottery. After the drawing, remaining dates can be reserved throughout the season.</p><div className="mt-6 border-l-4 border-[#a36b43] pl-5"><p className="font-semibold">Lottery deadline: first Friday in November</p><p className="mt-3 leading-7">Applications open October 1. Applicants are notified of the results by November 21.</p><p className="mt-3 leading-7">After November 21, call <a href="tel:4063293914" className="underline underline-offset-4">406.329.3914</a> to ask about remaining dates.</p></div></div>
        <div className="leading-7"><p>Mail a signed application, cabin choice, two date choices, and payment to BLM, Cabin Rental Program, 3255 Fort Missoula Road, Missoula, MT 59804. Checks: Department of Interior, BLM.</p><p className="mt-4 text-[#625b50]">Successful applicants receive an information packet with maps, directions, and the cabin’s lock combination for their dates. Checks are returned to unsuccessful applicants.</p><p className="mt-4 text-[#625b50]">Reservations require payment. Refunds need seven days’ notice; a $5 processing fee is nonrefundable.</p><a className="mt-6 inline-block bg-[#3d5a3e] px-5 py-4 font-semibold text-white hover:bg-[#24352b]" href="https://www.garnetghosttown.org/cabin-rentals.php" target="_blank" rel="noreferrer">Application details & permit terms ↗</a></div>
      </div>
      <section aria-label="Cabin equipment and packing lists" className="mt-12 grid gap-10 border-t border-[#24352b]/20 pt-10 md:grid-cols-2">
        {[{title: "Items provided at the cabin", items: provided}, {title: "Suggested items to bring", items: bring}].map(({title, items}) => <div key={title}><h2 className="display-type text-3xl md:text-4xl">{title}</h2><ul className="mt-6 list-disc space-y-2 pl-5 leading-7 text-[#625b50]">{items.map(item => <li key={item}>{item}</li>)}</ul></div>)}
      </section>
      <div className="mt-12 border-t border-[#24352b]/20 pt-8 leading-7 text-[#625b50]"><p>Pack out your trash. Checkout is at noon. Confirm current rates, access, and pet rules with the BLM before your trip.</p><a href="mailto:BLM_MT_Missoula_FO@blm.gov" className="mt-5 inline-block break-all underline underline-offset-4">BLM_MT_Missoula_FO@blm.gov</a></div>
    </section>
  </main>;
}
