import type { Metadata } from "next";
import Link from "next/link";
import { getVisitorUpdates, updateCategories } from "@/lib/content/updates";
import { formatEventDate, formatEventDayTime } from "@/lib/content/time";
export const metadata: Metadata = {title:"Current Updates",description:"Check Garnet visitor updates, road and snow reports, announcements, maps, and meeting records."};
export const revalidate = 60;
export default async function UpdatesPage(){
  const {updates,unavailable}=await getVisitorUpdates();
  const visitor=updates.filter(item=>item.category!=="meeting"); const meetings=updates.filter(item=>item.category==="meeting");
  return <main id="main-content" className="bg-[#f4f0e7] text-[#24352b]">
    <section className="bg-[#1e2f1f] px-5 pt-44 pb-12 text-white md:px-10 md:pt-48"><div className="mx-auto max-w-[82rem]"><p className="text-sm font-semibold text-[#e0c46d]">Before you head to Garnet</p><h1 className="display-type mt-4 text-5xl md:text-7xl">Current updates</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/80">Road and snow reports, visitor alerts, announcements, and meeting records from the Garnet Preservation Association. Check the date on each update before making plans.</p><div className="mt-6 flex flex-wrap gap-6 text-sm font-semibold"><a href="#visitor-updates" className="underline underline-offset-4">Visitor updates</a><a href="#meetings" className="underline underline-offset-4">Meetings & minutes</a><Link href="/events" className="underline underline-offset-4">Event calendar</Link></div></div></section>
    <section id="visitor-updates" className="mx-auto max-w-[82rem] scroll-mt-36 px-5 py-12 md:px-10">
      <h2 className="display-type text-3xl md:text-4xl">Visitor updates</h2>
      {updates.some(item => item.sample) && <p className="mt-5 border-l-4 border-[#a36b43] bg-[#e9e1d1] p-5 font-semibold">Sample content for review. These examples do not report current conditions or announce real meetings.</p>}
      <p className="mt-4 max-w-3xl leading-7 text-[#625b50]">This area covers road access, snow and grooming, fire notes, trail maps, events, seasonal news, general alerts, and land-sale scam information.</p>
      {unavailable ? <p role="status" className="mt-6 border-l-4 border-[#a36b43] bg-[#e9e1d1] p-5">Current updates are unavailable. Call the BLM at <a href="tel:4063293914" className="underline">406.329.3914</a> to confirm conditions.</p> : !visitor.length && <p className="mt-6 border-l-4 border-[#a36b43] bg-[#e9e1d1] p-5">No visitor updates have been published here yet. This does not confirm that roads are open or conditions are clear. Call the BLM at <a href="tel:4063293914" className="underline">406.329.3914</a> before traveling.</p>}
      <div className="mt-8 divide-y divide-[#24352b]/20">{visitor.map(item=><article id={`update-${item.id}`} key={item.id} className="scroll-mt-36 grid gap-4 py-8 md:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-semibold uppercase tracking-wider text-[#98613d]">{updateCategories[item.category]}</p><h3 className="display-type mt-3 text-3xl">{item.title}</h3>{item.sample && <p className="mt-2 text-xs font-semibold uppercase tracking-wider text-[#98613d]">Demonstration only</p>}<p className="mt-3 text-sm text-[#625b50]">{item.verifiedAt ? `Last checked ${formatEventDate(item.verifiedAt)}` : "Last checked date not provided"}</p>{item.modifiedAt && <p className="mt-1 text-xs text-[#625b50]">Updated {formatEventDate(item.modifiedAt)}</p>}</div><div>{item.stale && !item.sample && <p className="mb-4 border-l-4 border-[#a36b43] pl-4 font-semibold">Not recently confirmed. Check with the BLM before relying on this report.</p>}<p className="leading-8">{item.summary}</p>{item.details && <details className="mt-4"><summary className="w-fit cursor-pointer font-semibold underline underline-offset-4">Read full update</summary><div className="mt-4 space-y-4 leading-8 text-[#625b50]">{item.details.split(/\n\s*\n/).map((text,i)=><p key={i} className="whitespace-pre-line">{text}</p>)}</div></details>}{item.resourceUrl && <a href={item.resourceUrl} className="mt-4 inline-block font-semibold text-[#3d5a3e] underline underline-offset-4">{item.resourceLabel} ↗</a>}</div></article>)}</div>
    </section>
    <section id="meetings" className="scroll-mt-36 border-t border-[#24352b]/20 bg-[#e9e1d1] px-5 py-12 md:px-10"><div className="mx-auto max-w-[82rem]"><h2 className="display-type text-3xl md:text-4xl">Meetings & minutes</h2>{!meetings.length && <p className="mt-5 leading-7 text-[#625b50]">{unavailable ? "Meeting records are unavailable right now." : "Meeting dates and minutes will appear here when published."}</p>}<div className="mt-6 divide-y divide-[#24352b]/20">{meetings.map(item=><article key={item.id} className="py-6"><h3 className="display-type text-2xl">{item.title}</h3>{item.sample && <p className="mt-2 text-xs font-semibold uppercase tracking-wider text-[#98613d]">Demonstration only</p>}{item.meetingAt && <p className="mt-2 font-semibold">{formatEventDate(item.meetingAt)} · {formatEventDayTime(item.meetingAt)}</p>}<p className="mt-3 leading-7">{item.summary}</p>{item.details && <p className="mt-3 whitespace-pre-line leading-7 text-[#625b50]">{item.details}</p>}{item.modifiedAt && <p className="mt-3 text-xs text-[#625b50]">Updated {formatEventDate(item.modifiedAt)}</p>}{item.resourceUrl && <a href={item.resourceUrl} className="mt-4 inline-block font-semibold underline underline-offset-4">{item.resourceLabel} ↗</a>}</article>)}</div></div></section>
    <aside className="mx-auto max-w-[82rem] px-5 py-10 leading-7 md:px-10">For travel questions, call <a href="tel:4063293914" className="font-semibold underline">406.329.3914</a>. Check <a href="https://www.blm.gov/visit/garnet-ghost-town" className="underline">official BLM visitor information</a> and <Link href="/visit" className="underline">plan your visit</Link>.</aside>
  </main>;
}
